### ISSUE TITLE
Xubuntu20用不了

### ISSUE THREAD

**Issue by chengwds** [shannon-6block/lotus-miner#12]
goroutine 2429 [chan receive]:
github.com/filecoin-project/lotus/node/modules.RunHello.func1(0x2beee80, 0xc030a9c480, 0xc030a9c390, 0x7f6c6017c170, 0xc000122000, 0x2bd4a80, 0xc000432c90)
	/home/ps/share/ssd/code/test.0.4.1.community/node/modules/services.go:40 +0xcb
created by github.com/filecoin-project/lotus/node/modules.RunHello
	/home/ps/share/ssd/code/test.0.4.1.community/node/modules/services.go:39 +0x258

goroutine 2430 [chan receive]:
github.com/filecoin-project/lotus/lib/peermgr.(*PeerMgr).Run(0xc018f6b260, 0x2c07940, 0xc057bc06c0)
	/home/ps/share/ssd/code/test.0.4.1.community/lib/peermgr/peermgr.go:113 +0xa6
created by github.com/filecoin-project/lotus/node/modules.RunPeerMgr
	/home/ps/share/ssd/code/test.0.4.1.community/node/modules/services.go:54 +0x7f

goroutine 2431 [select]:
github.com/libp2p/go-libp2p-pubsub.(*Subscription).Next(0xc057bc0740, 0x2c07940, 0xc057bc0700, 0x4a, 0x50, 0x9eb00941e51)
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.2/subscription.go:24 +0xd8
github.com/filecoin-project/lotus/chain/sub.HandleIncomingBlocks(0x2c07940, 0xc057bc0700, 0xc057bc0740, 0xc030668300, 0x2c224e0, 0xc000020000)
	/home/ps/share/ssd/code/test.0.4.1.community/chain/sub/incoming.go:44 +0x5a
created by github.com/filecoin-project/lotus/node/modules.HandleIncomingBlocks
	/home/ps/share/ssd/code/test.0.4.1.community/node/modules/services.go:80 +0x2ef

goroutine 2432 [chan receive]:
github.com/whyrusleeping/pubsub.(*PubSub).start(0xc030661080)
	/home/ps/go/pkg/mod/github.com/whyrusleeping/pubsub@v0.0.0-20131020042734-02de8aa2db3d/pubsub.go:106 +0x1b5
created by github.com/whyrusleeping/pubsub.New
	/home/ps/go/pkg/mod/github.com/whyrusleeping/pubsub@v0.0.0-20131020042734-02de8aa2db3d/pubsub.go:42 +0x95

rax    0x40a
rbx    0x7f6c397f8940
rcx    0x4
rdx    0x0
rdi    0x7f6c397f8ae0
rsi    0x7f6c397f8a80
rbp    0x7f6c397f8c60
rsp    0x7f6c397f8940
r8     0x4b1ba7b6434bac01
r9     0x5f48985753c758ba
r10    0x7ce5e6eaf9060043
r11    0x8194f07d5e7c38f
r12    0x7f6c397f8a80
r13    0x7f6c397f8b10
r14    0x7f6c397f8ae0
r15    0x7f6c397f89a0
rip    0x2070f18
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0
root@cheng-W2600CR:~#

**Comment by shannon-6block** [comment]
请用推荐的操作系统，其他难以保证正常运行
