### ISSUE TITLE
some deals failed

### ISSUE THREAD

**Issue by jackoelv** [shannon-6block/lotus-miner#14]
In lotus-storage-miner sectors list, we will see:

265: FaultedFinal sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [5689 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
266: FaultedFinal sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [5698 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
267: FaultedFinal sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [5703 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

I have checked it with SealPreCommit1 Failed, I run lotus-storage-miner sectors update-state --really-do-it 266 FaultedFinal for the FaultedFinal.

In worker`s log , we will see:
2020-07-16T09:08:58.007+0800	DEBUG	advmgr	sector-storage/localworker.go:72	acquired sector {117803 265} (e:1; a:0): {{0 0} /jacklotus/lotusworker/unsealed/s-t0117803-265  }
2020-07-16T09:08:58.012+0800	WARN	rpc	go-jsonrpc/handler.go:226	error in RPC call to 'Filecoin.SealPreCommit1': acquiring sector paths:
    github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).SealPreCommit1
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/ffiwrapper/sealer_cgo.go:429
  - local acquire error:
    github.com/filecoin-project/sector-storage/stores.(*Remote).AcquireSector
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/stores/remote.go:87
  - couldn't find a suitable path for a sector:
    github.com/filecoin-project/sector-storage/stores.(*Local).AcquireSector
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/stores/local.go:315
2020-07-16T09:09:56.012+0800	DEBUG	advmgr	sector-storage/localworker.go:72	acquired sector {117803 267} (e:1; a:0): {{0 0} /jacklotus/lotusworker/unsealed/s-t0117803-267  }
2020-07-16T09:09:56.017+0800	WARN	rpc	go-jsonrpc/handler.go:226	error in RPC call to 'Filecoin.SealPreCommit1': acquiring sector paths:
    github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).SealPreCommit1
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/ffiwrapper/sealer_cgo.go:429
  - local acquire error:
    github.com/filecoin-project/sector-storage/stores.(*Remote).AcquireSector
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/stores/remote.go:87
  - couldn't find a suitable path for a sector:
    github.com/filecoin-project/sector-storage/stores.(*Local).AcquireSector
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/stores/local.go:315

I have met this problem in my debug, Maybe the cause that sched assign a wrong req to the worker. 

the bug caused by assgin AddPiece to a worker but not to a miner.
when pledge, It`s running normally.
but if deals some, some time the error will  occured.

**Comment by jackoelv** [comment]
It`s a bug caused by assign AddPiece to a worker. 
if pledge ,no problem.
but if deals, sometimes have a error like that ,sometimes it runs normaly.

**Comment by shannon-6block** [comment]
When a deal comes, the miner will look for a worker for sealing. If there is no worker suitable, it will go to the state `PackingFailed` and keep retrying.
