### ISSUE TITLE
能不能添加一个功能让worker做完任务后不移动扇区，因为我使用的是分布式文件系统

### ISSUE THREAD

**Issue by sedasdas** [shannon-6block/lotus-miner#16]
机器多了移到同一个地方速度太慢，分布式文件系统不需要移动

**Comment by shannon-6block** [comment]
封装的时候，扇区在SSD上；封装结束后，扇区总要转移到另一个位置的。
不知道所谓的不移动是如何操作的。

**Comment by sedasdas** [comment]
@shannon-6block 我的意思是留在worker本地的另一个指定位置，而不是全部放到一个远程的统一位置

**Comment by shannon-6block** [comment]
哦哦，这个后续会做的，现在来不及了

**Comment by sedasdas** [comment]
@shannon-6block 感谢大神，因为很多人都没有部署独立的存储系统:smile:
