### ISSUE TITLE
windowPOST ERROR

### ISSUE THREAD

**Issue by alwaysjh** [shannon-6block/lotus-miner#22]
calibration 8.13.3

2020-08-15T21:23:56.942+0800	ERROR	storageminer	storage/wdpost_run.go:55	submitPost failed: pushing message to mpool:
    github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).submitPost
        /home/ps/code/community/8.13.3/storage/wdpost_run.go:472
  - estimating gas used: message execution failed: exit 16, reason: post commit randomness mismatched (RetCode=16)
2020-08-15T21:23:56.942+0800	ERROR	storageminer	storage/wdpost_run.go:28	TODO

**Comment by alwaysjh** [comment]
另外存储接单似乎也接不了，https://calibration.spacerace.filecoin.io/deals/t02307 提示为ClientQueryAsk failed : failed to read ask response: stream reset

**Comment by shannon-6block** [comment]
接单的问题我看Slack上有说
