### ISSUE TITLE
4.6 installed in 5.1 version

### ISSUE THREAD

**Issue by callmestu** [shannon-6block/lotus-miner#27]
I downloaded the script at:

https://github.com/shannon-6block/lotus-miner/blob/master/README_en.md

But I still get an old version of Lotus:

/mnt/data/lotus-miner/script# lotus -v
lotus version 0.4.6+git.b4ca4a3b

even though I see in the install.sh script:

rm -rf lotus-miner.tar.gz cmd
wget https://github.com/shannon-6block/lotus-miner/releases/download/testnet.0.5.1/lotus-miner.tar.gz
mkdir cmd
tar zxvf lotus-miner.tar.gz -C cmd/
cp cmd/* /usr/local/bin/

**Comment by shannon-6block** [comment]
please use the command `which lotus`
