### ISSUE TITLE
试图在保留已有有效存储的情况下从官版切换到试用版0.7.0出错

### ISSUE THREAD

**Issue by fanfu13** [shannon-6block/lotus-miner#30]
问题产生条件：官版0.7.0 切换到试用版0.7.0 
问题详情：
1.启动daemon，正常；
2. 启动miner会出错，错误情况如下：
2020-09-16T16:56:23.127+0800	INFO	stores	stores/index.go:148	New sector storage: fb0d2d2e-822c-4c3b-9bcc-ec8ad5b42f52
2020-09-16T16:56:23.129+0800	INFO	stores	stores/index.go:148	New sector storage: b947e5f4-02cd-42b0-b74c-5f26a8c240e4
ERROR: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules".HandleDeals (/home/ps/code/community/lotus/node/modules/storageminer.go:235): failed to build storagemarket.StorageProvider: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.14/src/reflect/asm_amd64.s:12): failed to build *storedask.StoredAsk: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.14/src/reflect/asm_amd64.s:12): failed to build storagemarket.StorageProviderNode: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.14/src/reflect/asm_amd64.s:12): failed to build *sectorblocks.SectorBlocks: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.14/src/reflect/asm_amd64.s:12): failed to build *storage.Miner: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.14/src/reflect/asm_amd64.s:12): failed to build sectorstorage.SectorManager: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.14/src/reflect/asm_amd64.s:12): failed to build *sectorstorage.Manager: received non-nil error from function "reflect".makeFuncStub (/usr/lib/go-1.14/src/reflect/asm_amd64.s:12): opening path /home/worker/p2dir/test2/.lotusminer: parse sector id fetching: sscanf sector name ('fetching'): input does not match format

**Comment by shannon-6block** [comment]
需要把盘里面名字带fetching的临时文件手动删一下
