### ISSUE TITLE
lotus-miner算力全部掉了

### ISSUE THREAD

**Issue by chengwds** [shannon-6block/lotus-miner#42]
root@chen:~# lotus-miner info
Miner: f033224
Sector Size: 32 GiB
Byte Power:   0 B / 592.1 PiB (0.0000%)
Actual Power: 0  / 592 Pi (0.0000%)
	Committed: 16.69 TiB
	Proving: 13.72 TiB (13.72 TiB Faulty, 82.20%)
Below minimum power threshold, no blocks will be won
Deals: 1, 128 KiB
	Active: 0, 0 B (Verified: 0, 0 B)

Miner Balance: 121.945116005759412969 FIL
	PreCommit:   12.634312611511189367 FIL
	Pledge:      91.3715043873677137 FIL
	Vesting:     0 FIL
	Available:   17.939299006880509902 FIL
Worker Balance: 0.04447802314095571 FIL
Market (Escrow):  0.000000008916807734 FIL
Market (Locked):  0.000000008916807734 FIL

Expected Seal Duration: 10h0m0s

Sectors:
	Total: 1327 (1)
	Proving: 476 (0)
	PreCommit1: 83 (0)
	PreCommit2: 67 (0)
	Committing: 47 (0)
	Removed: 504 (0)
	SealPreCommit2Failed: 9 (0)
	PreCommitFailed: 40 (1)
	ComputeProofFailed: 5 (0)
	RemoveFailed: 7 (0)
	FatalError: 89 (0)

**Comment by shannon-6block** [comment]
这没币了啊

**Comment by chengwds** [comment]
这个节点放弃了。这个新的节点11月5日掉算力了，我把日志发你看看怎么解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shannon-6block/lotus-miner"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 中午1:45
收件人:&nbsp;"shannon-6block/lotus-miner"<lotus-miner@noreply.github.com&gt;;
抄送:&nbsp;"智英合科技"<cheng1196@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shannon-6block/lotus-miner] lotus-miner算力全部掉了 (#42)





 
这没币了啊
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

miner.log (105.71M, 2020年12月06日 10:32 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=0f306464689951c163ea527247350717085307555607010b1c0655010418015a00094905550c0415060854550500050953535002613c3555585e01164f595a5f310d&code=10dda558
