### ISSUE TITLE
miner程序一直开着的，lotus区块程序也很正常,也会掉算力

### ISSUE THREAD

**Issue by chengwds** [shannon-6block/lotus-miner#47]
Sector Size: 32 GiB
Byte Power:   3.469 TiB / 651.5 PiB (0.0005%)
Actual Power: 3.47 Ti / 651 Pi (0.0005%)
	Committed: 49.19 TiB
	Proving: 49.19 TiB (45.72 TiB Faulty, 92.94%)
Below minimum power threshold, no blocks will be won
Deals: 3, 256.2 MiB
	Active: 2, 256.1 MiB (Verified: 0, 0 B)

Miner Balance: 303.947075999972695002 FIL
	PreCommit:   0.279854834014328148 FIL
	Pledge:      303.667221165958366854 FIL
	Vesting:     0 FIL
	Available:   -27.317131315439203773 FIL
Worker Balance: 41.461981911264889308 FIL
Market (Escrow):  0.000025827721255692 FIL
Market (Locked):  0.000025439196255692 FIL

Expected Seal Duration: 10h0m0s

Sectors:
	Total: 2485 (3)
	Proving: 1523 (2)
	Removed: 494 (0)
	SealPreCommit1Failed: 1 (1)
	SealPreCommit2Failed: 27 (0)
	PreCommitFailed: 49 (0)
	ComputeProofFailed: 80 (0)
	RemoveFailed: 241 (0)
	FatalError: 70 (0)
root@cheng111:~# lotus-miner actor control list
name       ID       key           use    balance                    
owner      f045550  f3qveixpo...  other  41.461981911264889308 FIL  
worker     f045550  f3qveixpo...  other  41.461981911264889308 FIL  
control-0  f055491  f3uh2o4h7...  post   99.999900730207571978 FIL

**Comment by ncgege** [comment]
掉不掉算力主要是看你window post 成功没。

**Comment by chengwds** [comment]
嗯嗯，怎样提交恢复证明啊？




Miner: f045555
Sector Size: 32 GiB
Byte Power:&nbsp; &nbsp;3.469 TiB / 695.8 PiB (0.0004%)
Actual Power: 3.47 Ti / 696 Pi (0.0004%)
	Committed: 49.19 TiB
	Proving: 49.19 TiB (45.72 TiB Faulty, 92.94%)
Below minimum power threshold, no blocks will be won
Deals: 4, 256.3 MiB
	Active: 2, 256.1 MiB (Verified: 0, 0 B)


Miner Balance: 303.667221165958366854 FIL
	PreCommit:&nbsp; &nbsp;0 FIL
	Pledge:&nbsp; &nbsp; &nbsp; 303.667221165958366854 FIL
	Vesting:&nbsp; &nbsp; &nbsp;0 FIL
	Available:&nbsp; &nbsp;-178.191369876729282322 FIL
Worker Balance: 41.46197629415164713 FIL
Market (Escrow):&nbsp; 0.000027433676235392 FIL
Market (Locked):&nbsp; 0.00002544889008138 FIL







一直在线，没有恢复了，ceph写入速度1.5G，读取速度400兆,是读取速度慢了吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shannon-6block/lotus-miner"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 下午5:13
收件人:&nbsp;"shannon-6block/lotus-miner"<lotus-miner@noreply.github.com&gt;;
抄送:&nbsp;"智英合科技"<cheng1196@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shannon-6block/lotus-miner] miner程序一直开着的，lotus区块程序也很正常,也会掉算力 (#47)





 
掉不掉算力主要是看你window post 成功没。

**Comment by modytor** [comment]
Miner Available:;-**178.191369876729282322 FIL**   给miner转钱，让他变成正的， 下次提交WindowPoSt应该会正常，查看miner日志。亲测有效。

**Comment by shannon-6block** [comment]
对的，第一次可能是因为存储访问不上掉算力，第二次再抽查的时候得保证钱够
