### ISSUE TITLE
快照地址好像不能用！

### ISSUE THREAD

**Issue by 18758285235** [shannon-6block/lotus-miner#49]

**Comment by 18758285235** [comment]
通过这个链接wget https://very-temporary-spacerace-chain-snapshot.s3.amazonaws.com/Spacerace_pruned_stateroots_snapshot_latest.car.

![2020-11-02 11-39-46 的屏幕截图](https://user-images.githubusercontent.com/42059401/97827766-2bfae300-1d00-11eb-85c7-6d49c43fc8d3.png)

**Comment by shannon-6block** [comment]
这是官方给的，找官方
