### ISSUE TITLE
1.2.1 执行出错

### ISSUE THREAD

**Issue by alwaysjh** [shannon-6block/lotus-miner#50]
lotus -v
lotus: error while loading sheared libraries: libhwloc.so.5: cannot open shared object file: No such file or directory

**Comment by quantumgw** [comment]
Missing dependencies

sudo apt install hwloc libhwloc-dev

**Comment by alwaysjh** [comment]
hwloc libhwloc-dev 这两个装了，还是一样的错

**Comment by alwaysjh** [comment]
搞定了，/usr/lib/x86_64-linux-gnu目录下缺少libhwloc.so.5，复制了一个libhwloc.so成libhwloc.so.5就可以了
