### ISSUE TITLE
升级后worker报错

### ISSUE THREAD

**Issue by quantumgw** [shannon-6block/lotus-miner#52]
升级后pc1和pc2会并行，过一会就报错：
miner log：
2020-11-24T19:44:23.853+0800    INFO    advmgr  sector-storage/sched_worker.go:441      stats   {"type": "run task start", "wid": [165,163,242,2,52,255,72,231,177,32,79,10,62,186,99,4], "worker": "10.10.10.22:3456", "taskType": "seal/v0/precommit/2", "sectorMiner": "18501", "sectorNumber": "3341"}
2020-11-24T19:47:39.511+0800    INFO    advmgr  sector-storage/sched_worker.go:443      stats   {"type": "run task end", "wid": [165,163,242,2,52,255,72,231,177,32,79,10,62,186,99,4], "worker": "10.10.10.22:3456", "taskType": "seal/v0/precommit/2", "sectorMiner": "18501", "sectorNumber": "3341"}
2020-11-24T19:47:39.512+0800    WARN    sectors storage-sealing/fsm.go:523      sector 3341 got error event sealing.SectorSealPreCommit2Failed: seal pre commit(2) failed: storage call error 0: presealing sector 3341 (): Rust panic: no unwind information
2020-11-24T19:47:39.519+0800    INFO    sectors storage-sealing/states_failed.go:27     SealPreCommit2Failed(3341), waiting 59.480119969s before retrying
2020-11-24T19:48:39.000+0800    WARN    sectors storage-sealing/states_failed.go:80     sector 3341 failed for Rust panic, retry PreCommit1
2020-11-24T19:48:39.004+0800    INFO    sectors storage-sealing/states_failed.go:27     SealPreCommit1Failed(3341), waiting 59.995997487s before retrying
2020-11-24T19:49:39.006+0800    INFO    advmgr  sector-storage/sched_worker.go:441      stats   {"type": "run task start", "wid": [165,163,242,2,52,255,72,231,177,32,79,10,62,186,99,4], "worker": "10.10.10.22:3456", "taskType": "seal/v0/finalize", "sectorMiner": "18501", "sectorNumber": "3341"}

worker log：
thread '<unnamed>' panicked at 'failed to flatten and write store: Bad file descriptor (os error 9)', /home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:580:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:502:34

lotus@lotus:~$ lotus-miner sectors status --log 3341
SectorID:       3341
Status:         Removing
CIDcommD:       <nil>
CIDcommR:       <nil>
Ticket:         e8c9391a4c909bfcaae8fa85d7cf0f9a29c48d0b81e743bad9d5dcf0efd43400
TicketH:        261452
Seed:
SeedH:          0
Precommit:      <nil>
Commit:         <nil>
Proof:
Deals:          [0]
Retries:        0
--------
Event Log:
0.      2020-11-24 08:16:29 +0800 CST:  [event;sealing.SectorStartCC]   {"User":{"ID":3341,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"baga6ea4seaqao7s73y24kcutaosvacpdjgfe5pw76ooefnyqw4ynr3d2y6x2mpq"}},"DealInfo":null}]}}
1.      2020-11-24 08:16:29 +0800 CST:  [event;sealing.SectorPacked]    {"User":{"FillerPieces":null}}
2.      2020-11-24 14:18:23 +0800 CST:  [event;sealing.SectorPreCommit1]        {"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjEiLCJsYWJlbHMiOnsiU3RhY2tlZERyZzMyR2lCVjEiOnsibGFiZWxzIjpbeyJwYXRoIjoiL2ZpbGVjb2luL3dvcms1L2NhY2hlL3MtdDAxODUwMS0zMzQxIiwiaWQiOiJsYXllci0xIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZmlsZWNvaW4vd29yazUvY2FjaGUvcy10MDE4NTAxLTMzNDEiLCJpZCI6ImxheWVyLTIiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9maWxlY29pbi93b3JrNS9jYWNoZS9zLXQwMTg1MDEtMzM0MSIsImlkIjoibGF5ZXItMyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2ZpbGVjb2luL3dvcms1L2NhY2hlL3MtdDAxODUwMS0zMzQxIiwiaWQiOiJsYXllci00Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZmlsZWNvaW4vd29yazUvY2FjaGUvcy10MDE4NTAxLTMzNDEiLCJpZCI6ImxheWVyLTUiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9maWxlY29pbi93b3JrNS9jYWNoZS9zLXQwMTg1MDEtMzM0MSIsImlkIjoibGF5ZXItNiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2ZpbGVjb2luL3dvcms1L2NhY2hlL3MtdDAxODUwMS0zMzQxIiwiaWQiOiJsYXllci03Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZmlsZWNvaW4vd29yazUvY2FjaGUvcy10MDE4NTAxLTMzNDEiLCJpZCI6ImxheWVyLTgiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9maWxlY29pbi93b3JrNS9jYWNoZS9zLXQwMTg1MDEtMzM0MSIsImlkIjoibGF5ZXItOSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2ZpbGVjb2luL3dvcms1L2NhY2hlL3MtdDAxODUwMS0zMzQxIiwiaWQiOiJsYXllci0xMCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2ZpbGVjb2luL3dvcms1L2NhY2hlL3MtdDAxODUwMS0zMzQxIiwiaWQiOiJsYXllci0xMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N31dLCJfaCI6bnVsbH19LCJjb25maWciOnsicGF0aCI6Ii9maWxlY29pbi93b3JrNS9jYWNoZS9zLXQwMTg1MDEtMzM0MSIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjE0NzQ4MzY0Nywicm93c190b19kaXNjYXJkIjo3fSwiY29tbV9kIjpbNywxMjYsOTUsMjIyLDUzLDE5NywxMCwxNDcsMywxNjUsODAsOSwyMjcsNzMsMTM4LDc4LDE5MCwyMjMsMjQzLDE1Niw2NiwxODMsMTYsMTgzLDQ4LDIxNiwyMzYsMTIyLDE5OSwxNzUsMTY2LDYyXX0=","TicketValue":"6Mk5GkyQm/yq6PqF188PminEjQuB50O62dXc8O/UNAA=","TicketEpoch":261452}}
3.      2020-11-24 18:09:58 +0800 CST:  [event;sealing.SectorRestart]   {"User":{}}
4.      2020-11-24 18:10:03 +0800 CST:  [event;sealing.SectorSealPreCommit2Failed]      {"User":{}}
        seal pre commit(2) failed: runSched didn't find any good workers
5.      2020-11-24 18:11:03 +0800 CST:  [event;sealing.SectorRetrySealPreCommit2]       {"User":{}}
6.      2020-11-24 18:11:03 +0800 CST:  [event;sealing.SectorSealPreCommit2Failed]      {"User":{}}
        seal pre commit(2) failed: runSched didn't find any good workers
7.      2020-11-24 18:12:03 +0800 CST:  [event;sealing.SectorRetrySealPreCommit2]       {"User":{}}
8.      2020-11-24 18:12:03 +0800 CST:  [event;sealing.SectorSealPreCommit2Failed]      {"User":{}}
        seal pre commit(2) failed: runSched didn't find any good workers
9.      2020-11-24 18:13:03 +0800 CST:  [event;sealing.SectorRetrySealPreCommit2]       {"User":{}}
10.     2020-11-24 18:13:03 +0800 CST:  [event;sealing.SectorSealPreCommit2Failed]      {"User":{}}
        seal pre commit(2) failed: runSched didn't find any good workers
11.     2020-11-24 18:14:03 +0800 CST:  [event;sealing.SectorRetrySealPreCommit2]       {"User":{}}
12.     2020-11-24 18:14:03 +0800 CST:  [event;sealing.SectorSealPreCommit2Failed]      {"User":{}}
        seal pre commit(2) failed: runSched didn't find any good workers
13.     2020-11-24 18:15:03 +0800 CST:  [event;sealing.SectorRetrySealPreCommit2]       {"User":{}}
14.     2020-11-24 18:15:03 +0800 CST:  [event;sealing.SectorSealPreCommit2Failed]      {"User":{}}
        seal pre commit(2) failed: runSched didn't find any good workers
15.     2020-11-24 18:16:03 +0800 CST:  [event;sealing.SectorRetrySealPreCommit2]       {"User":{}}
16.     2020-11-24 18:16:03 +0800 CST:  [event;sealing.SectorSealPreCommit2Failed]      {"User":{}}
        seal pre commit(2) failed: runSched didn't find any good workers
17.     2020-11-24 18:17:03 +0800 CST:  [event;sealing.SectorRetrySealPreCommit2]       {"User":{}}
18.     2020-11-24 19:47:39 +0800 CST:  [event;sealing.SectorSealPreCommit2Failed]      {"User":{}}
        seal pre commit(2) failed: storage call error 0: presealing sector 3341 (): Rust panic: no unwind information
19.     2020-11-24 19:48:39 +0800 CST:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
20.     2020-11-24 19:49:39 +0800 CST:  [event;sealing.SectorRemove]    {"User":{}}

**Comment by shannon-6block** [comment]
见最新更新的版本
