### ISSUE TITLE
求助：安装之后执行lotus wallet new bls报ERROR: handler: websocket connection closed是什么原因

### ISSUE THREAD

**Issue by billysoa** [shannon-6block/lotus-miner#54]
root@hws:/# lotus -v
lotus version 1.2.1+6block+git.3dee72f61.1606186728+2
root@hws:/# nohup lotus daemon > ~/lotus.log 2>&1 &
[3] 2267
root@hws:/# lotus net peers | wc -l
0
root@hws:/# lotus net peers | wc -l
35
root@hws:/# lotus wallet new bls
ERROR: handler: websocket connection closed

[3]-  Exit 2                  nohup lotus daemon > ~/lotus.log 2>&1
root@hws:/# 
在线求助大佬，谢谢。

**Comment by shannon-6block** [comment]
lotus 没顺利启动
