### ISSUE TITLE
网端口50666映射到了本地端口50888,请问这个映射端口是起什么作用的？如果在一个大型的内网中映射不了这个端口，还能挖矿么？

### ISSUE THREAD

**Issue by richie963** [shannon-6block/lotus-miner#58]
进阶：公网ip端口绑定，假设公网ip为183.38.3.106，并将公网端口50666映射到了本地端口50888，修改lotus的config.toml，将Libp2p下的ListenAddresses和AnnounceAddresses配置如下

ListenAddresses = ["/ip4/0.0.0.0/tcp/50888"]
AnnounceAddresses = ["/ip4/183.38.3.106/tcp/50666", "/ip4/127.0.0.1/tcp/50888"]

**Comment by shannon-6block** [comment]
会影响挖矿效率
