### ISSUE TITLE
Cannot switch to official miner

### ISSUE THREAD

**Issue by askender** [shannon-6block/lotus-miner#6]
Background:
- I can use official miner and 6block miner both
- My machine is 3970X and 256G RAM and 64 Swap when I change from `--max-parallel 2` to `--max-parallel 3`(cannot run), and then change back, the worker will shutting down when running (can successfully finish sealing only 1 or 2 times)
- so I change to official code, and found the errors below (I checked the path config is ok):

**Just marked it here, and I will re-init and test `the code switch` again**

```
2020-06-26T11:10:09.205+0800	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/garbage.go:24	Pledge {106509 20}, contains []
2020-06-26T11:10:09.205+0800	DEBUG	stores	stores/index.go:370	not allocating on a7ba966e-82cc-419e-9a6f-2d06cd055188, didn't receive heartbeats for 7h25m10.295901813s
2020-06-26T11:10:09.205+0800	ERROR	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/garbage.go:68	add piece:
    github.com/filecoin-project/storage-fsm.(*Sealing).pledgeSector
        /**/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200625160832-379a4655b044/garbage.go:30
  - finding best alloc storage:
    github.com/filecoin-project/sector-storage.(*allocSelector).Ok
        /**/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200625154333-98ef8e4ef246/selector_alloc.go:49
  - no good path found:
    github.com/filecoin-project/sector-storage/stores.(*Index).StorageBestAlloc
        /**/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200625154333-98ef8e4ef246/stores/index.go:383
```

**Comment by askender** [comment]
I know there are two `lotusstorage` for 6block miner.
the default one is on nvme(for speedup?) to store datastore and keystore, and the storage.json point to the path of real final data path.
This default setting is better.  After I tweak sectorstore.json, the problem is solved.    **Ready to close the issue.**
But the related problem are:  
- does two lotusstorage path useful?
- how to backup datastore and keystore, what is the data struct of datastore and keystore? I am learning https://github.com/dgraph-io/badger now.
- the lotusworker path is on nvme, does it speedup? is there any benchmark?

**Comment by shannon-6block** [comment]
It's just for convenience. Typically we need to `attach` multiple paths for the sector storage. These paths are usually network disks.

So it's a better choice to use a local directory on SSD as `LOTUS_STORAGE_PATH` for config files and key-value files. In addition, it will speed up read and write of key-value files.

**Comment by shannon-6block** [comment]
As a community version, I'll allow the use of official `lotus daemon` together with the `lotus-storage-miner` provided by us in future releases.

**Comment by askender** [comment]
Thanks!  Problem solved.
