### ISSUE TITLE
lotus: error while loading shared libraries: libhwloc.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by hysci** [shannon-6block/lotus-miner#60]
OS: ubuntu 20.04
Test:
* apt-get install libhwloc-dev
* apt-get install libhwloc5
* wget https://download.open-mpi.org/release/hwloc/v2.4/hwloc-2.4.0.tar.gz && ./configure && make && make install

**Comment by mason0510** [comment]
download again 使用代理

**Comment by shannon-6block** [comment]
see https://github.com/shannon-6block/lotus-miner/commit/43cc2b04d4b315aa31d1a35c662dc3a3cb9670c3

**Comment by Lazydayz137** [comment]
Still doing this on a clean install of 20

Have to manually find deb and install it.

**Comment by SteaceP** [comment]
I build it on Ubuntu 20.04.2 but transfered it to many more PCs with also Ubuntu 20.04.2
It would start for the same reason
just install this:
sudo apt-get install libhwloc-dev
on the other PCs and good to go
