### ISSUE TITLE
单机使用推荐配置的总并发数是多少？

### ISSUE THREAD

**Issue by zhiwei55** [shannon-6block/lotus-miner#62]
CPU：AMD 3960X 
内存：256 GB
SSD：1 TB * 2
GPU：NVIDIA 2080
操作系统：Ubuntu 18.04

单机运行 miner,worker,storage的话总并发p多少合适？两个SSD能达到 p*2吗？

**Comment by shannon-6block** [comment]
请看README中对于并发数的描述
