### ISSUE TITLE
【请教】一直显示FinalizeSector  NO       NO      n/a  状态，miner里面的config要设置哪里才会上链？谢谢了

### ISSUE THREAD

**Issue by landy68888** [shannon-6block/lotus-miner#66]
ID   State           OnChain  Active  Expiration  Deals
1    FinalizeSector  NO       NO      n/a         CC
3    FinalizeSector  NO       NO      n/a         CC
4    FinalizeSector  NO       NO      n/a         CC
5    FinalizeSector  NO       NO      n/a         CC
6    FinalizeSector  NO       NO      n/a         CC
7    FinalizeSector  NO       NO      n/a         CC
8    FinalizeSector  NO       NO      n/a         CC
9    FinalizeSector  NO       NO      n/a         CC
11   FinalizeSector  NO       NO      n/a         CC
12   FinalizeSector  NO       NO      n/a         CC
13   FinalizeSector  NO       NO      n/a         CC
14   FinalizeSector  NO       NO      n/a         CC
23   FinalizeSector  NO       NO      n/a         CC
28   FinalizeSector  NO       NO      n/a         CC
39   FinalizeSector  NO       NO      n/a         CC
46   FinalizeSector  NO       NO      n/a         CC
47   FinalizeSector  NO       NO      n/a         CC
48   FinalizeSector  NO       NO      n/a         CC
51   FinalizeSector  NO       NO      n/a         CC
52   FinalizeSector  NO       NO      n/a         CC
53   FinalizeSector  NO       NO      n/a         CC
60   FinalizeSector  NO       NO      n/a         CC
64   FinalizeSector  NO       NO      n/a         CC
68   FinalizeSector  NO       NO      n/a         CC
72   FinalizeSector  NO       NO      n/a         CC
73   FinalizeSector  NO       NO      n/a         CC
74   FinalizeSector  NO       NO      n/a         CC
75   FinalizeSector  NO       NO      n/a         CC
76   FinalizeSector  NO       NO      n/a         CC
77   FinalizeSector  NO       NO      n/a         CC
78   FinalizeSector  NO       NO      n/a         CC
79   FinalizeSector  NO       NO      n/a         CC

**Comment by shannon-6block** [comment]
你的情况是，PreCommit消息已提交，但是扇区最终没有落盘，所以Commit消息没提交
