### ISSUE TITLE
【问题】两张显卡的woeker能不能指派一张做P2一张做C2？

### ISSUE THREAD

**Issue by landy68888** [shannon-6block/lotus-miner#68]
【问题】两张显卡的woeker能不能指派一张做P2一张做C2？看到worker不会同时做两个P2或者两个C2或者一个P2一个C2？支持吗？并且错C2的适合MSI显示两个卡在做，但是一张卡温度是凉的，感觉没启动

**Comment by shannon-6block** [comment]
社区免费版本不包含算法上的优化
