### ISSUE TITLE
About Benchmark

### ISSUE THREAD

**Issue by askender** [shannon-6block/lotus-miner#7]
For this compiled version, is there any benchmark with official one?

by the way:
```

# 可选的环境变量
# 以下设置会让worker使用GPU计算PreCommit2。
export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1 #  benchmark ??
export FIL_PROOFS_USE_GPU_TREE_BUILDER=1 # benchmark ??

# 以下设置会让worker不使用GPU计算Commit2，而改用CPU。
# export BELLMAN_NO_GPU=true # benchmark ??

```
What is the benchmark of using GPU and not-using GPU?  curious
what is best config? I think default is the best, which is same as:
```
export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
export FIL_PROOFS_USE_GPU_TREE_BUILDER=1
```

**Comment by shannon-6block** [comment]
This version will never do any changes to the algorithm. So the benchmark is the same as the official one.

**Comment by askender** [comment]
Got it.  Thanks!
